# Generated by Django 2.2.2 on 2019-06-05 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('js', 'Java Script'), ('py', 'Python'), ('java', 'Java'), ('html', 'Hml'), ('css', 'Css'), ('ruby', 'Ruby'), ('php', 'Php'), ('go', 'Go'), ('c', 'C'), ('text', 'Plain Text')], default='text', max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to=settings.AUTH_USER_MODEL)),
                ('shrared_with', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
