# Generated by Django 2.2.2 on 2019-06-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_auto_20190605_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='shrared_with',
            new_name='shared_with',
        ),
    ]
